/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-04-15 19:10:39 UTC)
 * on 2014-04-24 at 16:17:40 UTC 
 * Modify at your own risk.
 */

package com.androidproductions.servicemonitor.backend.services;

/**
 * Service definition for Services (v1.1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link ServicesRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Services extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the services library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://mobile-messaging.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "services/v1.1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Services(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Services(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "listServices".
   *
   * This request holds the parameters needed by the services server.  After setting any optional
   * parameters, call the {@link ListServices#execute()} method to invoke the remote operation.
   *
   * @param serviceGroup
   * @return the request
   */
  public ListServices listServices(java.lang.String serviceGroup) throws java.io.IOException {
    ListServices result = new ListServices(serviceGroup);
    initialize(result);
    return result;
  }

  public class ListServices extends ServicesRequest<com.androidproductions.servicemonitor.backend.services.model.CollectionResponseServiceRecord> {

    private static final String REST_PATH = "servicerecord/{serviceGroup}";

    /**
     * Create a request for the method "listServices".
     *
     * This request holds the parameters needed by the the services server.  After setting any
     * optional parameters, call the {@link ListServices#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListServices#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param serviceGroup
     * @since 1.13
     */
    protected ListServices(java.lang.String serviceGroup) {
      super(Services.this, "GET", REST_PATH, null, com.androidproductions.servicemonitor.backend.services.model.CollectionResponseServiceRecord.class);
      this.serviceGroup = com.google.api.client.util.Preconditions.checkNotNull(serviceGroup, "Required parameter serviceGroup must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListServices setAlt(java.lang.String alt) {
      return (ListServices) super.setAlt(alt);
    }

    @Override
    public ListServices setFields(java.lang.String fields) {
      return (ListServices) super.setFields(fields);
    }

    @Override
    public ListServices setKey(java.lang.String key) {
      return (ListServices) super.setKey(key);
    }

    @Override
    public ListServices setOauthToken(java.lang.String oauthToken) {
      return (ListServices) super.setOauthToken(oauthToken);
    }

    @Override
    public ListServices setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListServices) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListServices setQuotaUser(java.lang.String quotaUser) {
      return (ListServices) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListServices setUserIp(java.lang.String userIp) {
      return (ListServices) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String serviceGroup;

    /**

     */
    public java.lang.String getServiceGroup() {
      return serviceGroup;
    }

    public ListServices setServiceGroup(java.lang.String serviceGroup) {
      this.serviceGroup = serviceGroup;
      return this;
    }

    @Override
    public ListServices set(String parameterName, Object value) {
      return (ListServices) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "register".
   *
   * This request holds the parameters needed by the services server.  After setting any optional
   * parameters, call the {@link Register#execute()} method to invoke the remote operation.
   *
   * @param serviceId
   * @param serviceGroup
   * @return the request
   */
  public Register register(java.lang.String serviceId, java.lang.String serviceGroup) throws java.io.IOException {
    Register result = new Register(serviceId, serviceGroup);
    initialize(result);
    return result;
  }

  public class Register extends ServicesRequest<Void> {

    private static final String REST_PATH = "registerService/{serviceId}/{serviceGroup}";

    /**
     * Create a request for the method "register".
     *
     * This request holds the parameters needed by the the services server.  After setting any
     * optional parameters, call the {@link Register#execute()} method to invoke the remote operation.
     * <p> {@link
     * Register#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param serviceId
     * @param serviceGroup
     * @since 1.13
     */
    protected Register(java.lang.String serviceId, java.lang.String serviceGroup) {
      super(Services.this, "POST", REST_PATH, null, Void.class);
      this.serviceId = com.google.api.client.util.Preconditions.checkNotNull(serviceId, "Required parameter serviceId must be specified.");
      this.serviceGroup = com.google.api.client.util.Preconditions.checkNotNull(serviceGroup, "Required parameter serviceGroup must be specified.");
    }

    @Override
    public Register setAlt(java.lang.String alt) {
      return (Register) super.setAlt(alt);
    }

    @Override
    public Register setFields(java.lang.String fields) {
      return (Register) super.setFields(fields);
    }

    @Override
    public Register setKey(java.lang.String key) {
      return (Register) super.setKey(key);
    }

    @Override
    public Register setOauthToken(java.lang.String oauthToken) {
      return (Register) super.setOauthToken(oauthToken);
    }

    @Override
    public Register setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Register) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Register setQuotaUser(java.lang.String quotaUser) {
      return (Register) super.setQuotaUser(quotaUser);
    }

    @Override
    public Register setUserIp(java.lang.String userIp) {
      return (Register) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String serviceId;

    /**

     */
    public java.lang.String getServiceId() {
      return serviceId;
    }

    public Register setServiceId(java.lang.String serviceId) {
      this.serviceId = serviceId;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String serviceGroup;

    /**

     */
    public java.lang.String getServiceGroup() {
      return serviceGroup;
    }

    public Register setServiceGroup(java.lang.String serviceGroup) {
      this.serviceGroup = serviceGroup;
      return this;
    }

    @Override
    public Register set(String parameterName, Object value) {
      return (Register) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "unregister".
   *
   * This request holds the parameters needed by the services server.  After setting any optional
   * parameters, call the {@link Unregister#execute()} method to invoke the remote operation.
   *
   * @param serviceId
   * @return the request
   */
  public Unregister unregister(java.lang.String serviceId) throws java.io.IOException {
    Unregister result = new Unregister(serviceId);
    initialize(result);
    return result;
  }

  public class Unregister extends ServicesRequest<Void> {

    private static final String REST_PATH = "unregisterService/{serviceId}";

    /**
     * Create a request for the method "unregister".
     *
     * This request holds the parameters needed by the the services server.  After setting any
     * optional parameters, call the {@link Unregister#execute()} method to invoke the remote
     * operation. <p> {@link
     * Unregister#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param serviceId
     * @since 1.13
     */
    protected Unregister(java.lang.String serviceId) {
      super(Services.this, "POST", REST_PATH, null, Void.class);
      this.serviceId = com.google.api.client.util.Preconditions.checkNotNull(serviceId, "Required parameter serviceId must be specified.");
    }

    @Override
    public Unregister setAlt(java.lang.String alt) {
      return (Unregister) super.setAlt(alt);
    }

    @Override
    public Unregister setFields(java.lang.String fields) {
      return (Unregister) super.setFields(fields);
    }

    @Override
    public Unregister setKey(java.lang.String key) {
      return (Unregister) super.setKey(key);
    }

    @Override
    public Unregister setOauthToken(java.lang.String oauthToken) {
      return (Unregister) super.setOauthToken(oauthToken);
    }

    @Override
    public Unregister setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Unregister) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Unregister setQuotaUser(java.lang.String quotaUser) {
      return (Unregister) super.setQuotaUser(quotaUser);
    }

    @Override
    public Unregister setUserIp(java.lang.String userIp) {
      return (Unregister) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String serviceId;

    /**

     */
    public java.lang.String getServiceId() {
      return serviceId;
    }

    public Unregister setServiceId(java.lang.String serviceId) {
      this.serviceId = serviceId;
      return this;
    }

    @Override
    public Unregister set(String parameterName, Object value) {
      return (Unregister) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "update".
   *
   * This request holds the parameters needed by the services server.  After setting any optional
   * parameters, call the {@link Update#execute()} method to invoke the remote operation.
   *
   * @param serviceId
   * @param status
   * @return the request
   */
  public Update update(java.lang.String serviceId, java.lang.Integer status) throws java.io.IOException {
    Update result = new Update(serviceId, status);
    initialize(result);
    return result;
  }

  public class Update extends ServicesRequest<Void> {

    private static final String REST_PATH = "void/{serviceId}/{status}";

    /**
     * Create a request for the method "update".
     *
     * This request holds the parameters needed by the the services server.  After setting any
     * optional parameters, call the {@link Update#execute()} method to invoke the remote operation.
     * <p> {@link
     * Update#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param serviceId
     * @param status
     * @since 1.13
     */
    protected Update(java.lang.String serviceId, java.lang.Integer status) {
      super(Services.this, "PUT", REST_PATH, null, Void.class);
      this.serviceId = com.google.api.client.util.Preconditions.checkNotNull(serviceId, "Required parameter serviceId must be specified.");
      this.status = com.google.api.client.util.Preconditions.checkNotNull(status, "Required parameter status must be specified.");
    }

    @Override
    public Update setAlt(java.lang.String alt) {
      return (Update) super.setAlt(alt);
    }

    @Override
    public Update setFields(java.lang.String fields) {
      return (Update) super.setFields(fields);
    }

    @Override
    public Update setKey(java.lang.String key) {
      return (Update) super.setKey(key);
    }

    @Override
    public Update setOauthToken(java.lang.String oauthToken) {
      return (Update) super.setOauthToken(oauthToken);
    }

    @Override
    public Update setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Update) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Update setQuotaUser(java.lang.String quotaUser) {
      return (Update) super.setQuotaUser(quotaUser);
    }

    @Override
    public Update setUserIp(java.lang.String userIp) {
      return (Update) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String serviceId;

    /**

     */
    public java.lang.String getServiceId() {
      return serviceId;
    }

    public Update setServiceId(java.lang.String serviceId) {
      this.serviceId = serviceId;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer status;

    /**

     */
    public java.lang.Integer getStatus() {
      return status;
    }

    public Update setStatus(java.lang.Integer status) {
      this.status = status;
      return this;
    }

    @Override
    public Update set(String parameterName, Object value) {
      return (Update) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Services}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Services}. */
    @Override
    public Services build() {
      return new Services(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link ServicesRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setServicesRequestInitializer(
        ServicesRequestInitializer servicesRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(servicesRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
