/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-04-15 19:10:39 UTC)
 * on 2014-05-02 at 13:57:59 UTC 
 * Modify at your own risk.
 */

package com.androidproductions.servicemonitor.backend.services;

/**
 * Service definition for Services (v1.7).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link ServicesRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Services extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the services library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://mobile-messaging.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "services/v1.7/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Services(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Services(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "deleteServiceGroup".
   *
   * This request holds the parameters needed by the services server.  After setting any optional
   * parameters, call the {@link DeleteServiceGroup#execute()} method to invoke the remote operation.
   *
   * @param group
   * @return the request
   */
  public DeleteServiceGroup deleteServiceGroup(java.lang.String group) throws java.io.IOException {
    DeleteServiceGroup result = new DeleteServiceGroup(group);
    initialize(result);
    return result;
  }

  public class DeleteServiceGroup extends ServicesRequest<Void> {

    private static final String REST_PATH = "services/{group}";

    /**
     * Create a request for the method "deleteServiceGroup".
     *
     * This request holds the parameters needed by the the services server.  After setting any
     * optional parameters, call the {@link DeleteServiceGroup#execute()} method to invoke the remote
     * operation. <p> {@link DeleteServiceGroup#initialize(com.google.api.client.googleapis.services.A
     * bstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param group
     * @since 1.13
     */
    protected DeleteServiceGroup(java.lang.String group) {
      super(Services.this, "DELETE", REST_PATH, null, Void.class);
      this.group = com.google.api.client.util.Preconditions.checkNotNull(group, "Required parameter group must be specified.");
    }

    @Override
    public DeleteServiceGroup setAlt(java.lang.String alt) {
      return (DeleteServiceGroup) super.setAlt(alt);
    }

    @Override
    public DeleteServiceGroup setFields(java.lang.String fields) {
      return (DeleteServiceGroup) super.setFields(fields);
    }

    @Override
    public DeleteServiceGroup setKey(java.lang.String key) {
      return (DeleteServiceGroup) super.setKey(key);
    }

    @Override
    public DeleteServiceGroup setOauthToken(java.lang.String oauthToken) {
      return (DeleteServiceGroup) super.setOauthToken(oauthToken);
    }

    @Override
    public DeleteServiceGroup setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (DeleteServiceGroup) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public DeleteServiceGroup setQuotaUser(java.lang.String quotaUser) {
      return (DeleteServiceGroup) super.setQuotaUser(quotaUser);
    }

    @Override
    public DeleteServiceGroup setUserIp(java.lang.String userIp) {
      return (DeleteServiceGroup) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String group;

    /**

     */
    public java.lang.String getGroup() {
      return group;
    }

    public DeleteServiceGroup setGroup(java.lang.String group) {
      this.group = group;
      return this;
    }

    @Override
    public DeleteServiceGroup set(String parameterName, Object value) {
      return (DeleteServiceGroup) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "get".
   *
   * This request holds the parameters needed by the services server.  After setting any optional
   * parameters, call the {@link Get#execute()} method to invoke the remote operation.
   *
   * @param serviceGroup
   * @param serviceId
   * @return the request
   */
  public Get get(java.lang.String serviceGroup, java.lang.String serviceId) throws java.io.IOException {
    Get result = new Get(serviceGroup, serviceId);
    initialize(result);
    return result;
  }

  public class Get extends ServicesRequest<com.androidproductions.servicemonitor.backend.services.model.ServiceRecord> {

    private static final String REST_PATH = "services/{serviceGroup}/{serviceId}";

    /**
     * Create a request for the method "get".
     *
     * This request holds the parameters needed by the the services server.  After setting any
     * optional parameters, call the {@link Get#execute()} method to invoke the remote operation. <p>
     * {@link Get#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param serviceGroup
     * @param serviceId
     * @since 1.13
     */
    protected Get(java.lang.String serviceGroup, java.lang.String serviceId) {
      super(Services.this, "GET", REST_PATH, null, com.androidproductions.servicemonitor.backend.services.model.ServiceRecord.class);
      this.serviceGroup = com.google.api.client.util.Preconditions.checkNotNull(serviceGroup, "Required parameter serviceGroup must be specified.");
      this.serviceId = com.google.api.client.util.Preconditions.checkNotNull(serviceId, "Required parameter serviceId must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public Get setAlt(java.lang.String alt) {
      return (Get) super.setAlt(alt);
    }

    @Override
    public Get setFields(java.lang.String fields) {
      return (Get) super.setFields(fields);
    }

    @Override
    public Get setKey(java.lang.String key) {
      return (Get) super.setKey(key);
    }

    @Override
    public Get setOauthToken(java.lang.String oauthToken) {
      return (Get) super.setOauthToken(oauthToken);
    }

    @Override
    public Get setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Get) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Get setQuotaUser(java.lang.String quotaUser) {
      return (Get) super.setQuotaUser(quotaUser);
    }

    @Override
    public Get setUserIp(java.lang.String userIp) {
      return (Get) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String serviceGroup;

    /**

     */
    public java.lang.String getServiceGroup() {
      return serviceGroup;
    }

    public Get setServiceGroup(java.lang.String serviceGroup) {
      this.serviceGroup = serviceGroup;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String serviceId;

    /**

     */
    public java.lang.String getServiceId() {
      return serviceId;
    }

    public Get setServiceId(java.lang.String serviceId) {
      this.serviceId = serviceId;
      return this;
    }

    @Override
    public Get set(String parameterName, Object value) {
      return (Get) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listServiceGroups".
   *
   * This request holds the parameters needed by the services server.  After setting any optional
   * parameters, call the {@link ListServiceGroups#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public ListServiceGroups listServiceGroups() throws java.io.IOException {
    ListServiceGroups result = new ListServiceGroups();
    initialize(result);
    return result;
  }

  public class ListServiceGroups extends ServicesRequest<com.androidproductions.servicemonitor.backend.services.model.CollectionResponseServiceGroupRecord> {

    private static final String REST_PATH = "services";

    /**
     * Create a request for the method "listServiceGroups".
     *
     * This request holds the parameters needed by the the services server.  After setting any
     * optional parameters, call the {@link ListServiceGroups#execute()} method to invoke the remote
     * operation. <p> {@link ListServiceGroups#initialize(com.google.api.client.googleapis.services.Ab
     * stractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListServiceGroups() {
      super(Services.this, "GET", REST_PATH, null, com.androidproductions.servicemonitor.backend.services.model.CollectionResponseServiceGroupRecord.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListServiceGroups setAlt(java.lang.String alt) {
      return (ListServiceGroups) super.setAlt(alt);
    }

    @Override
    public ListServiceGroups setFields(java.lang.String fields) {
      return (ListServiceGroups) super.setFields(fields);
    }

    @Override
    public ListServiceGroups setKey(java.lang.String key) {
      return (ListServiceGroups) super.setKey(key);
    }

    @Override
    public ListServiceGroups setOauthToken(java.lang.String oauthToken) {
      return (ListServiceGroups) super.setOauthToken(oauthToken);
    }

    @Override
    public ListServiceGroups setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListServiceGroups) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListServiceGroups setQuotaUser(java.lang.String quotaUser) {
      return (ListServiceGroups) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListServiceGroups setUserIp(java.lang.String userIp) {
      return (ListServiceGroups) super.setUserIp(userIp);
    }

    @Override
    public ListServiceGroups set(String parameterName, Object value) {
      return (ListServiceGroups) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listServices".
   *
   * This request holds the parameters needed by the services server.  After setting any optional
   * parameters, call the {@link ListServices#execute()} method to invoke the remote operation.
   *
   * @param serviceGroup
   * @return the request
   */
  public ListServices listServices(java.lang.String serviceGroup) throws java.io.IOException {
    ListServices result = new ListServices(serviceGroup);
    initialize(result);
    return result;
  }

  public class ListServices extends ServicesRequest<com.androidproductions.servicemonitor.backend.services.model.CollectionResponseServiceRecord> {

    private static final String REST_PATH = "services/{serviceGroup}";

    /**
     * Create a request for the method "listServices".
     *
     * This request holds the parameters needed by the the services server.  After setting any
     * optional parameters, call the {@link ListServices#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListServices#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param serviceGroup
     * @since 1.13
     */
    protected ListServices(java.lang.String serviceGroup) {
      super(Services.this, "GET", REST_PATH, null, com.androidproductions.servicemonitor.backend.services.model.CollectionResponseServiceRecord.class);
      this.serviceGroup = com.google.api.client.util.Preconditions.checkNotNull(serviceGroup, "Required parameter serviceGroup must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListServices setAlt(java.lang.String alt) {
      return (ListServices) super.setAlt(alt);
    }

    @Override
    public ListServices setFields(java.lang.String fields) {
      return (ListServices) super.setFields(fields);
    }

    @Override
    public ListServices setKey(java.lang.String key) {
      return (ListServices) super.setKey(key);
    }

    @Override
    public ListServices setOauthToken(java.lang.String oauthToken) {
      return (ListServices) super.setOauthToken(oauthToken);
    }

    @Override
    public ListServices setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListServices) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListServices setQuotaUser(java.lang.String quotaUser) {
      return (ListServices) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListServices setUserIp(java.lang.String userIp) {
      return (ListServices) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String serviceGroup;

    /**

     */
    public java.lang.String getServiceGroup() {
      return serviceGroup;
    }

    public ListServices setServiceGroup(java.lang.String serviceGroup) {
      this.serviceGroup = serviceGroup;
      return this;
    }

    @Override
    public ListServices set(String parameterName, Object value) {
      return (ListServices) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "patch".
   *
   * This request holds the parameters needed by the services server.  After setting any optional
   * parameters, call the {@link Patch#execute()} method to invoke the remote operation.
   *
   * @param srvGroup
   * @param srvId
   * @param serviceGroup
   * @param serviceId
   * @param content the {@link com.androidproductions.servicemonitor.backend.services.model.ServiceRecord}
   * @return the request
   */
  public Patch patch(java.lang.String srvGroup, java.lang.String srvId, java.lang.String serviceGroup, java.lang.String serviceId, com.androidproductions.servicemonitor.backend.services.model.ServiceRecord content) throws java.io.IOException {
    Patch result = new Patch(srvGroup, srvId, serviceGroup, serviceId, content);
    initialize(result);
    return result;
  }

  public class Patch extends ServicesRequest<com.androidproductions.servicemonitor.backend.services.model.ServiceRecord> {

    private static final String REST_PATH = "services/{srvGroup}/{srvId}";

    /**
     * Create a request for the method "patch".
     *
     * This request holds the parameters needed by the the services server.  After setting any
     * optional parameters, call the {@link Patch#execute()} method to invoke the remote operation.
     * <p> {@link
     * Patch#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param srvGroup
     * @param srvId
     * @param serviceGroup
     * @param serviceId
     * @param content the {@link com.androidproductions.servicemonitor.backend.services.model.ServiceRecord}
     * @since 1.13
     */
    protected Patch(java.lang.String srvGroup, java.lang.String srvId, java.lang.String serviceGroup, java.lang.String serviceId, com.androidproductions.servicemonitor.backend.services.model.ServiceRecord content) {
      super(Services.this, "PATCH", REST_PATH, content, com.androidproductions.servicemonitor.backend.services.model.ServiceRecord.class);
      this.srvGroup = com.google.api.client.util.Preconditions.checkNotNull(srvGroup, "Required parameter srvGroup must be specified.");
      this.srvId = com.google.api.client.util.Preconditions.checkNotNull(srvId, "Required parameter srvId must be specified.");
      this.serviceGroup = com.google.api.client.util.Preconditions.checkNotNull(serviceGroup, "Required parameter serviceGroup must be specified.");
      this.serviceId = com.google.api.client.util.Preconditions.checkNotNull(serviceId, "Required parameter serviceId must be specified.");
    }

    @Override
    public Patch setAlt(java.lang.String alt) {
      return (Patch) super.setAlt(alt);
    }

    @Override
    public Patch setFields(java.lang.String fields) {
      return (Patch) super.setFields(fields);
    }

    @Override
    public Patch setKey(java.lang.String key) {
      return (Patch) super.setKey(key);
    }

    @Override
    public Patch setOauthToken(java.lang.String oauthToken) {
      return (Patch) super.setOauthToken(oauthToken);
    }

    @Override
    public Patch setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Patch) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Patch setQuotaUser(java.lang.String quotaUser) {
      return (Patch) super.setQuotaUser(quotaUser);
    }

    @Override
    public Patch setUserIp(java.lang.String userIp) {
      return (Patch) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String srvGroup;

    /**

     */
    public java.lang.String getSrvGroup() {
      return srvGroup;
    }

    public Patch setSrvGroup(java.lang.String srvGroup) {
      this.srvGroup = srvGroup;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String srvId;

    /**

     */
    public java.lang.String getSrvId() {
      return srvId;
    }

    public Patch setSrvId(java.lang.String srvId) {
      this.srvId = srvId;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String serviceGroup;

    /**

     */
    public java.lang.String getServiceGroup() {
      return serviceGroup;
    }

    public Patch setServiceGroup(java.lang.String serviceGroup) {
      this.serviceGroup = serviceGroup;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String serviceId;

    /**

     */
    public java.lang.String getServiceId() {
      return serviceId;
    }

    public Patch setServiceId(java.lang.String serviceId) {
      this.serviceId = serviceId;
      return this;
    }

    @Override
    public Patch set(String parameterName, Object value) {
      return (Patch) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "registerService".
   *
   * This request holds the parameters needed by the services server.  After setting any optional
   * parameters, call the {@link RegisterService#execute()} method to invoke the remote operation.
   *
   * @param group
   * @param content the {@link com.androidproductions.servicemonitor.backend.services.model.ServiceRecord}
   * @return the request
   */
  public RegisterService registerService(java.lang.String group, com.androidproductions.servicemonitor.backend.services.model.ServiceRecord content) throws java.io.IOException {
    RegisterService result = new RegisterService(group, content);
    initialize(result);
    return result;
  }

  public class RegisterService extends ServicesRequest<com.androidproductions.servicemonitor.backend.services.model.ServiceRecord> {

    private static final String REST_PATH = "services/{group}";

    /**
     * Create a request for the method "registerService".
     *
     * This request holds the parameters needed by the the services server.  After setting any
     * optional parameters, call the {@link RegisterService#execute()} method to invoke the remote
     * operation. <p> {@link RegisterService#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param group
     * @param content the {@link com.androidproductions.servicemonitor.backend.services.model.ServiceRecord}
     * @since 1.13
     */
    protected RegisterService(java.lang.String group, com.androidproductions.servicemonitor.backend.services.model.ServiceRecord content) {
      super(Services.this, "POST", REST_PATH, content, com.androidproductions.servicemonitor.backend.services.model.ServiceRecord.class);
      this.group = com.google.api.client.util.Preconditions.checkNotNull(group, "Required parameter group must be specified.");
    }

    @Override
    public RegisterService setAlt(java.lang.String alt) {
      return (RegisterService) super.setAlt(alt);
    }

    @Override
    public RegisterService setFields(java.lang.String fields) {
      return (RegisterService) super.setFields(fields);
    }

    @Override
    public RegisterService setKey(java.lang.String key) {
      return (RegisterService) super.setKey(key);
    }

    @Override
    public RegisterService setOauthToken(java.lang.String oauthToken) {
      return (RegisterService) super.setOauthToken(oauthToken);
    }

    @Override
    public RegisterService setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RegisterService) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RegisterService setQuotaUser(java.lang.String quotaUser) {
      return (RegisterService) super.setQuotaUser(quotaUser);
    }

    @Override
    public RegisterService setUserIp(java.lang.String userIp) {
      return (RegisterService) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String group;

    /**

     */
    public java.lang.String getGroup() {
      return group;
    }

    public RegisterService setGroup(java.lang.String group) {
      this.group = group;
      return this;
    }

    @Override
    public RegisterService set(String parameterName, Object value) {
      return (RegisterService) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "registerServiceGroup".
   *
   * This request holds the parameters needed by the services server.  After setting any optional
   * parameters, call the {@link RegisterServiceGroup#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.androidproductions.servicemonitor.backend.services.model.ServiceGroupRecord}
   * @return the request
   */
  public RegisterServiceGroup registerServiceGroup(com.androidproductions.servicemonitor.backend.services.model.ServiceGroupRecord content) throws java.io.IOException {
    RegisterServiceGroup result = new RegisterServiceGroup(content);
    initialize(result);
    return result;
  }

  public class RegisterServiceGroup extends ServicesRequest<com.androidproductions.servicemonitor.backend.services.model.ServiceGroupRecord> {

    private static final String REST_PATH = "services";

    /**
     * Create a request for the method "registerServiceGroup".
     *
     * This request holds the parameters needed by the the services server.  After setting any
     * optional parameters, call the {@link RegisterServiceGroup#execute()} method to invoke the
     * remote operation. <p> {@link RegisterServiceGroup#initialize(com.google.api.client.googleapis.s
     * ervices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param content the {@link com.androidproductions.servicemonitor.backend.services.model.ServiceGroupRecord}
     * @since 1.13
     */
    protected RegisterServiceGroup(com.androidproductions.servicemonitor.backend.services.model.ServiceGroupRecord content) {
      super(Services.this, "POST", REST_PATH, content, com.androidproductions.servicemonitor.backend.services.model.ServiceGroupRecord.class);
    }

    @Override
    public RegisterServiceGroup setAlt(java.lang.String alt) {
      return (RegisterServiceGroup) super.setAlt(alt);
    }

    @Override
    public RegisterServiceGroup setFields(java.lang.String fields) {
      return (RegisterServiceGroup) super.setFields(fields);
    }

    @Override
    public RegisterServiceGroup setKey(java.lang.String key) {
      return (RegisterServiceGroup) super.setKey(key);
    }

    @Override
    public RegisterServiceGroup setOauthToken(java.lang.String oauthToken) {
      return (RegisterServiceGroup) super.setOauthToken(oauthToken);
    }

    @Override
    public RegisterServiceGroup setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RegisterServiceGroup) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RegisterServiceGroup setQuotaUser(java.lang.String quotaUser) {
      return (RegisterServiceGroup) super.setQuotaUser(quotaUser);
    }

    @Override
    public RegisterServiceGroup setUserIp(java.lang.String userIp) {
      return (RegisterServiceGroup) super.setUserIp(userIp);
    }

    @Override
    public RegisterServiceGroup set(String parameterName, Object value) {
      return (RegisterServiceGroup) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "unregister".
   *
   * This request holds the parameters needed by the services server.  After setting any optional
   * parameters, call the {@link Unregister#execute()} method to invoke the remote operation.
   *
   * @param serviceGroup
   * @param serviceId
   * @return the request
   */
  public Unregister unregister(java.lang.String serviceGroup, java.lang.String serviceId) throws java.io.IOException {
    Unregister result = new Unregister(serviceGroup, serviceId);
    initialize(result);
    return result;
  }

  public class Unregister extends ServicesRequest<Void> {

    private static final String REST_PATH = "services/{serviceGroup}/{serviceId}";

    /**
     * Create a request for the method "unregister".
     *
     * This request holds the parameters needed by the the services server.  After setting any
     * optional parameters, call the {@link Unregister#execute()} method to invoke the remote
     * operation. <p> {@link
     * Unregister#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param serviceGroup
     * @param serviceId
     * @since 1.13
     */
    protected Unregister(java.lang.String serviceGroup, java.lang.String serviceId) {
      super(Services.this, "DELETE", REST_PATH, null, Void.class);
      this.serviceGroup = com.google.api.client.util.Preconditions.checkNotNull(serviceGroup, "Required parameter serviceGroup must be specified.");
      this.serviceId = com.google.api.client.util.Preconditions.checkNotNull(serviceId, "Required parameter serviceId must be specified.");
    }

    @Override
    public Unregister setAlt(java.lang.String alt) {
      return (Unregister) super.setAlt(alt);
    }

    @Override
    public Unregister setFields(java.lang.String fields) {
      return (Unregister) super.setFields(fields);
    }

    @Override
    public Unregister setKey(java.lang.String key) {
      return (Unregister) super.setKey(key);
    }

    @Override
    public Unregister setOauthToken(java.lang.String oauthToken) {
      return (Unregister) super.setOauthToken(oauthToken);
    }

    @Override
    public Unregister setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Unregister) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Unregister setQuotaUser(java.lang.String quotaUser) {
      return (Unregister) super.setQuotaUser(quotaUser);
    }

    @Override
    public Unregister setUserIp(java.lang.String userIp) {
      return (Unregister) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String serviceGroup;

    /**

     */
    public java.lang.String getServiceGroup() {
      return serviceGroup;
    }

    public Unregister setServiceGroup(java.lang.String serviceGroup) {
      this.serviceGroup = serviceGroup;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String serviceId;

    /**

     */
    public java.lang.String getServiceId() {
      return serviceId;
    }

    public Unregister setServiceId(java.lang.String serviceId) {
      this.serviceId = serviceId;
      return this;
    }

    @Override
    public Unregister set(String parameterName, Object value) {
      return (Unregister) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "update".
   *
   * This request holds the parameters needed by the services server.  After setting any optional
   * parameters, call the {@link Update#execute()} method to invoke the remote operation.
   *
   * @param srvGroup
   * @param srvId
   * @param content the {@link com.androidproductions.servicemonitor.backend.services.model.ServiceRecord}
   * @return the request
   */
  public Update update(java.lang.String srvGroup, java.lang.String srvId, com.androidproductions.servicemonitor.backend.services.model.ServiceRecord content) throws java.io.IOException {
    Update result = new Update(srvGroup, srvId, content);
    initialize(result);
    return result;
  }

  public class Update extends ServicesRequest<com.androidproductions.servicemonitor.backend.services.model.ServiceRecord> {

    private static final String REST_PATH = "services/{srvGroup}/{srvId}";

    /**
     * Create a request for the method "update".
     *
     * This request holds the parameters needed by the the services server.  After setting any
     * optional parameters, call the {@link Update#execute()} method to invoke the remote operation.
     * <p> {@link
     * Update#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param srvGroup
     * @param srvId
     * @param content the {@link com.androidproductions.servicemonitor.backend.services.model.ServiceRecord}
     * @since 1.13
     */
    protected Update(java.lang.String srvGroup, java.lang.String srvId, com.androidproductions.servicemonitor.backend.services.model.ServiceRecord content) {
      super(Services.this, "PUT", REST_PATH, content, com.androidproductions.servicemonitor.backend.services.model.ServiceRecord.class);
      this.srvGroup = com.google.api.client.util.Preconditions.checkNotNull(srvGroup, "Required parameter srvGroup must be specified.");
      this.srvId = com.google.api.client.util.Preconditions.checkNotNull(srvId, "Required parameter srvId must be specified.");
    }

    @Override
    public Update setAlt(java.lang.String alt) {
      return (Update) super.setAlt(alt);
    }

    @Override
    public Update setFields(java.lang.String fields) {
      return (Update) super.setFields(fields);
    }

    @Override
    public Update setKey(java.lang.String key) {
      return (Update) super.setKey(key);
    }

    @Override
    public Update setOauthToken(java.lang.String oauthToken) {
      return (Update) super.setOauthToken(oauthToken);
    }

    @Override
    public Update setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Update) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Update setQuotaUser(java.lang.String quotaUser) {
      return (Update) super.setQuotaUser(quotaUser);
    }

    @Override
    public Update setUserIp(java.lang.String userIp) {
      return (Update) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String srvGroup;

    /**

     */
    public java.lang.String getSrvGroup() {
      return srvGroup;
    }

    public Update setSrvGroup(java.lang.String srvGroup) {
      this.srvGroup = srvGroup;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String srvId;

    /**

     */
    public java.lang.String getSrvId() {
      return srvId;
    }

    public Update setSrvId(java.lang.String srvId) {
      this.srvId = srvId;
      return this;
    }

    @Override
    public Update set(String parameterName, Object value) {
      return (Update) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateServiceGroup".
   *
   * This request holds the parameters needed by the services server.  After setting any optional
   * parameters, call the {@link UpdateServiceGroup#execute()} method to invoke the remote operation.
   *
   * @param group
   * @param content the {@link com.androidproductions.servicemonitor.backend.services.model.ServiceGroupRecord}
   * @return the request
   */
  public UpdateServiceGroup updateServiceGroup(java.lang.String group, com.androidproductions.servicemonitor.backend.services.model.ServiceGroupRecord content) throws java.io.IOException {
    UpdateServiceGroup result = new UpdateServiceGroup(group, content);
    initialize(result);
    return result;
  }

  public class UpdateServiceGroup extends ServicesRequest<Void> {

    private static final String REST_PATH = "services/{group}";

    /**
     * Create a request for the method "updateServiceGroup".
     *
     * This request holds the parameters needed by the the services server.  After setting any
     * optional parameters, call the {@link UpdateServiceGroup#execute()} method to invoke the remote
     * operation. <p> {@link UpdateServiceGroup#initialize(com.google.api.client.googleapis.services.A
     * bstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param group
     * @param content the {@link com.androidproductions.servicemonitor.backend.services.model.ServiceGroupRecord}
     * @since 1.13
     */
    protected UpdateServiceGroup(java.lang.String group, com.androidproductions.servicemonitor.backend.services.model.ServiceGroupRecord content) {
      super(Services.this, "PUT", REST_PATH, content, Void.class);
      this.group = com.google.api.client.util.Preconditions.checkNotNull(group, "Required parameter group must be specified.");
    }

    @Override
    public UpdateServiceGroup setAlt(java.lang.String alt) {
      return (UpdateServiceGroup) super.setAlt(alt);
    }

    @Override
    public UpdateServiceGroup setFields(java.lang.String fields) {
      return (UpdateServiceGroup) super.setFields(fields);
    }

    @Override
    public UpdateServiceGroup setKey(java.lang.String key) {
      return (UpdateServiceGroup) super.setKey(key);
    }

    @Override
    public UpdateServiceGroup setOauthToken(java.lang.String oauthToken) {
      return (UpdateServiceGroup) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateServiceGroup setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateServiceGroup) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateServiceGroup setQuotaUser(java.lang.String quotaUser) {
      return (UpdateServiceGroup) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateServiceGroup setUserIp(java.lang.String userIp) {
      return (UpdateServiceGroup) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String group;

    /**

     */
    public java.lang.String getGroup() {
      return group;
    }

    public UpdateServiceGroup setGroup(java.lang.String group) {
      this.group = group;
      return this;
    }

    @Override
    public UpdateServiceGroup set(String parameterName, Object value) {
      return (UpdateServiceGroup) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Services}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Services}. */
    @Override
    public Services build() {
      return new Services(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link ServicesRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setServicesRequestInitializer(
        ServicesRequestInitializer servicesRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(servicesRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
